### ISSUE TITLE
[Bug] Breaks when `%` is added

### ISSUE THREAD

**Issue by jef** [jubianchi/semver-check#98]
Although not valid, using `%` in `Constraint` or `Version` will break the webpage.

**Comment by steveluscher** [comment]
```
actions.js:29 URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at we.updateHistory (Router.js:12:44)
    at we.componentDidUpdate (Router.js:33:14)
    at iu (react-dom.production.min.js:212:231)
    at dc (react-dom.production.min.js:255:229)
    at scheduler.production.min.js:19:467
    at Wo (react-dom.production.min.js:122:325)
    at pc (react-dom.production.min.js:248:370)
    at Zu (react-dom.production.min.js:239:376)
    at react-dom.production.min.js:123:115
```

I would have fixed it just now, but I can't even start the dev server on my 64-bit machine because of something SASS related.

**Comment by WORMSS** [comment]
I just ran into this within 1 second of using the website.. accidently typed % instead of ^ and BOOM, straight to a white screen that pressing the back button doesn't fix... modifying the url directly was the only solution.
